home/urls.py
from django.urls import path
from django.conf.urls import include
from . import views

urlpatterns = [
    path('',views.hello,name='hello'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('register-api/', views.user_signup, name='register-api'),
    path('login-api/', views.user_login, name='login-api'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

web1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('home.urls')),
    path('user/',include('user.urls')),
    path('',RedirectView.as_view(url="/home/",permanent=True)),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.
def hello(request):
    context = {} 
    login_session = request.session.get('login_session','')

    if login_session == '':
        context['login_session'] = False
    else :
        context['login_session'] = True
    return render(request, 'home/index.html',context)

home/templates/home/index.html
<!DOCTYPE html> 
<html lang="kr">
<head>
    <meta charset="UTP-8">
    <meta name="viewport" content="width=device-width,initial-scale = 1.0">
    <title>Jobsulting</title>
</head>
<body>
    <h1>Jobsulting</h1>
    <a href="/"><button>홈으로</button></a>

    {% if login_session %}
    <a href = "{% url 'user:logout' %}"><button>로그아웃</button></a>
    {% else %}
    <a href="{% url 'user:login' %}"><button>로그인</button></a>
    <a href="{% url 'user:register' %}"><button>회원가입</button></a>
    <div style="border : 1px black solid; margin : 20px 0px;"></div>
    {% endif %}

    {% block contents %}
    {% endblock contents %} 
</body>
</html>